### ISSUE TITLE
Show token field as readonly when token was received via GET

### ISSUE THREAD

**Issue by markus2342** [mayflower/demockrazy#10]
When a user clicks on the voting link and the token is given in the GET request, the token input field should be readonly by default.

**Comment by LeuX** [comment]
ich geb das mal der @katrin-schneider, die hat das feld eh schon ausgeblendet :)

**Comment by katrin-schneider** [comment]
solved in mayflower/demockrazy/commit/305f478494ec8509bcf9f0f6cbd5dd2d964fb447
