### ISSUE TITLE
Add mark as broken button in manage view

### ISSUE THREAD

**Issue by markus2342** [mayflower/demockrazy#11]
If there was a mistake when creating the poll, should the poll creator have the possibility to mark the poll as broken?

This would mean, that users can't vote and results are not shown.
This would only be possible, on polls that have not been closed.

**Comment by LeuX** [comment]
why not just deleting the poll and all associated entities when the admin invalidates a poll?

**Comment by markus2342** [comment]
A benefit would be that when someone uses the link, the poll would be shown as ~~deleted~~ invalidated, instead of getting a 404.
But in the end, it's the same and 404 has a similar meaning. So deleting directly sounds tidier.

Edit: Freudian slip
