### ISSUE TITLE
See, if token already was resolved

### ISSUE THREAD

**Issue by Praiodan** [mayflower/demockrazy#2]
As participant
I want to see if my token was already used 
to be able to see the number of outstanding votes without beeing confused if I already voted or not. 

AC: 
GIVEN I click on the deep link in the email and open the vote 
WHEN I load the page
THEN I would like to see the phrase "your token was already resolved" instead of the voting options.

**Comment by LeuX** [comment]
As of now, the user will see 'this token is invalid', or a similar error message after clicking 'vote'.
We delete tokens when they have been used to cast a vote - that would have to change for this. 
@markus2342: what's your opinion?

**Comment by markus2342** [comment]
We can check if a token is valid the same way we check if the token is valid when the user presses the 'vote' button.
Currently we're just passing through the token in the GET request to the token input field.
We could parse it in this step, so we can implement the feature without the need to change the token delete logic.

**Comment by LeuX** [comment]
@Praiodan please test and close

**Comment by Praiodan** [comment]
Looks good enough, thanks. Closed.
