### ISSUE TITLE
Extend admin view by overview of outstanding votes

### ISSUE THREAD

**Issue by Praiodan** [mayflower/demockrazy#3]
As admin
I want to be able to see the poll overview and the outstanding votes
to be able to decide, how many votes are pending without being a necessary participant of the vote. 

AC:
GIVEN that I am an admin and got the admin email 
WHEN I click on the deep link of the poll
THEN the poll opens in my browser and I can see the number of done and outstanding votes.

**Comment by markus2342** [comment]
Implemented with 488768d .
